spring.application.name=authPortal

# Import local environment configuration file
spring.config.import=optional:file:.env.local[.properties]

# Database Configuration
spring.datasource.url=jdbc:h2:mem:urldb

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_ID}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true